### ISSUE TITLE
初期設定で「設定して次へ進む」を押すとエラーとなり初期設定が完了しない

### ISSUE THREAD

**Issue by ytooyama** [eisen-dev/eisen_docs#4]
「設定して次へ進む」ボタンを押した後に表示されるエラー
Warning: file_put_contents(connect.php): failed to open stream: Permission denied in /vagrant/webd/init-setup2.php on line 38

Warning: require_once(/vagrant/webd/connect.php): failed to open stream: No such file or directory in /vagrant/webd/init-setup2.php on line 40

Fatal error: require_once(): Failed opening required '/vagrant/webd/connect.php' (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/webd/init-setup2.php on line 40

**Comment by ytooyama** [comment]
インストールは次を参考にしました。
https://github.com/eisen-dev/eisen_docs/blob/master/jp/installation.md
eisen_frontのセットアップとeisen_engineのセットアップをする前に、Vagrantfileなどを利用するため、ドキュメントに書かれていない以下の作業を行っています。
eisen_frontのソースをgit clone
git clone https://github.com/eisen-dev/eisen_front.git
eisen_engineのソースをgit clone
git clone https://github.com/eisen-dev/eisen_engine.git

**Comment by ytooyama** [comment]
おそらくスクリプトの中でPHPのPPAを追加していますが想定しているバージョンではないものがインストールされた可能性があります。先ほどデプロイした時はPHP5.6がインストールされました。

# apt-cache policy php5
php5:
  Installed: 5.6.18+dfsg-1+deb.sury.org~precise+1
  Candidate: 5.6.18+dfsg-1+deb.sury.org~precise+1
  Version table:
 *** 5.6.18+dfsg-1+deb.sury.org~precise+1 0
        500 http://ppa.launchpad.net/ondrej/php5-5.6/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status
     5.3.10-1ubuntu3.21 0
        500 http://archive.ubuntu.com/ubuntu/ precise-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ precise-security/main amd64 Packages

**Comment by ytooyama** [comment]
eisen_frontのerror.log
[Tue Mar 01 01:10:03.628838 2016] [:error] [pid 11490] [client 10.0.2.2:50082] PHP Warning:  file_put_contents(connect.php): failed to open stream: Permission denied in /vagrant/webd/init-setup2.php on line 38, referer: http://localhost:8080/init-setup1.php
[Tue Mar 01 01:10:03.629633 2016] [:error] [pid 11490] [client 10.0.2.2:50082] PHP Warning:  require_once(/vagrant/webd/connect.php): failed to open stream: No such file or directory in /vagrant/webd/init-setup2.php on line 40, referer: http://localhost:8080/init-setup1.php
[Tue Mar 01 01:10:03.629683 2016] [:error] [pid 11490] [client 10.0.2.2:50082] PHP Fatal error:  require_once(): Failed opening required '/vagrant/webd/connect.php' (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/webd/init-setup2.php on line 40, referer: http://localhost:8080/init-setup1.php

**Comment by ytooyama** [comment]
Permission deniedが出ているので該当のファイルのパーミッションを見ましたが、vagrant.vagrantです。

-rw-r--r-- 1 vagrant vagrant  4565 Feb 29 08:51 init-setup2.php

**Comment by aliceinwire** [comment]
はい、init-setup2.phpを動くためにconnect.phpファイルがひつようです。init-setup1.phpがそのファイルを作っていますがパーミッション問題があれば作ろ事ができないです。

**Comment by ytooyama** [comment]
ありがとうございます。
git cloneしたソースはmasterを使ってみたのですが、タグalpha0.1を指定したほうがいいでしょうか。

**Comment by aliceinwire** [comment]
いえいえ、masterのようがいいです。

**Comment by aliceinwire** [comment]
`root@precise64:/home/vagrant# ls /vagrant -la 
total 243
drwxrwxrwx  1 vagrant vagrant  8192 Feb 20 17:00 .
drwxr-xr-x 24 root    root     4096 Feb 28 17:42 ..
-rwxrwxrwx  1 vagrant vagrant   134 Jan 12 05:38 bower.json
-rwxrwxrwx  1 vagrant vagrant   512 Jan 30 16:45 .codeclimate.yml
-rwxrwxrwx  1 vagrant vagrant   310 Jan 19 04:15 composer.json
-rwxrwxrwx  1 vagrant vagrant 69649 Jan 19 04:15 composer.lock
drwxrwxrwx  1 vagrant vagrant  4096 Mar  1 02:09 .git
-rwxrwxrwx  1 vagrant vagrant   192 Feb  4 00:46 .gitignore
-rwxrwxrwx  1 vagrant vagrant 35821 Feb 18 05:10 GPL-LICENSE.txt
drwxrwxrwx  1 vagrant vagrant  8192 Mar  1 02:09 .idea
-rwxrwxrwx  1 vagrant vagrant    96 Feb 18 05:10 LICENSE.md
-rwxrwxrwx  1 vagrant vagrant  1154 Feb 18 05:10 MIT-LICENSE.txt
drwxrwxrwx  1 vagrant vagrant 81920 Jan 12 05:53 node_modules
-rwxrwxrwx  1 vagrant vagrant   718 Feb 28 17:57 npm-debug.log
-rwxrwxrwx  1 vagrant vagrant   223 Jan  6 17:40 phpunit.xml
-rwxrwxrwx  1 vagrant vagrant   361 Jan 20 17:06 poMake.sh
-rwxrwxrwx  1 vagrant vagrant   216 Jun 26  2015 .project
-rwxrwxrwx  1 vagrant vagrant  1371 Feb 20 17:00 README.md
-rwxrwxrwx  1 vagrant vagrant    25 Dec 20 12:20 requirement.txt
drwxrwxrwx  1 vagrant vagrant  4096 Feb 18 05:39 tests
-rwxrwxrwx  1 vagrant vagrant  3007 Dec 11 04:36 tslint.json
drwxrwxrwx  1 vagrant vagrant     0 Feb 28 17:40 vagrant
drwxrwxrwx  1 vagrant vagrant     0 Jan  9 19:31 .vagrant
-rwxrwxrwx  1 vagrant vagrant  3273 Jan 13 05:26 Vagrantfile
drwxrwxrwx  1 vagrant vagrant  4096 Feb 28 17:57 vendor
drwxrwxrwx  1 vagrant vagrant 12288 Feb 28 16:41 webd
`

**Comment by aliceinwire** [comment]
vagrantのインストールログ見せてくれますか

**Comment by ytooyama** [comment]
EXCON_DEBUG=1 vagrant up --debugでeisen_front用のOSをデプロイした時のdebug logです。
[vagrantup-log-debug.txt](https://github.com/eisen-dev/eisen_docs/files/152080/vagrantup-log-debug.txt)

**Comment by ytooyama** [comment]
OS X Elcapitanで実行しているのが問題でしょうか。

**Comment by aliceinwire** [comment]
chmod -R 755 /vagrant/webd/

**Comment by aliceinwire** [comment]
chmod -R 755 /vagrant/webd/

**Comment by aliceinwire** [comment]
C:\xampp\htdocs\bayes_client>vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1

**Comment by ytooyama** [comment]
バージョンは一緒です。
$ vagrant version
Installed Version: 1.8.1
Latest Version: 1.8.1
 
You're running an up-to-date version of Vagrant!

デプロイした後に/vagrant/webd/ のパーミッションを修正しましたが、同じエラーが出ました。
$ vagrant up
-snip-
$ vagrant ssh
vagrant@vagrant-ubuntu-precise-64:~$ sudo chmod -R 755 /vagrant/webd/

Warning: file_put_contents(connect.php): failed to open stream: Permission denied in /vagrant/webd/init-setup2.php on line 38

Warning: require_once(/vagrant/webd/connect.php): failed to open stream: No such file or directory in /vagrant/webd/init-setup2.php on line 40

Fatal error: require_once(): Failed opening required '/vagrant/webd/connect.php' (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/webd/init-setup2.php on line 40

vagrant upした時のログです。
[vagrantup-log-debug-2.txt](https://github.com/eisen-dev/eisen_docs/files/152125/vagrantup-log-debug-2.txt)

**Comment by aliceinwire** [comment]
vagrant ssh
cd /vagrant
ls -la
後でここに出力結果をコピペしてください。

**Comment by aliceinwire** [comment]
```
root@precise64:/vagrant# ls -la webd
total 216
drwxrwxrwx 1 vagrant vagrant 12288 Mar  1 04:29 .
drwxrwxrwx 1 vagrant vagrant  8192 Feb 20 17:00 ..
-rwxrwxrwx 1 vagrant vagrant   442 Feb 18 05:41 ajaxtest2.php
-rwxrwxrwx 1 vagrant vagrant 10289 Feb 18 05:41 ajaxtest.php
-rwxrwxrwx 1 vagrant vagrant   105 Feb  4 00:47 config.ini
-rwxrwxrwx 1 vagrant vagrant   102 Mar  1 04:29 connect.php
-rwxrwxrwx 1 vagrant vagrant    30 Feb 28 16:38 example.php
-rwxrwxrwx 1 vagrant vagrant  9689 Feb 18 05:41 host_manager.php
drwxrwxrwx 1 vagrant vagrant  4096 Feb  2 04:32 images
drwxrwxrwx 1 vagrant vagrant 12288 Feb 22 04:23 includes
-rwxrwxrwx 1 vagrant vagrant 20058 Feb 18 09:52 index.php
-rwxrwxrwx 1 vagrant vagrant    20 Feb 28 16:26 info.php
-rwxrwxrwx 1 vagrant vagrant  3702 Feb 18 05:42 init-setup1.php
-rwxrwxrwx 1 vagrant vagrant  4693 Feb 18 05:46 init-setup2.php
-rwxrwxrwx 1 vagrant vagrant  2411 Feb 18 05:42 init-setup3.php
-rwxrwxrwx 1 vagrant vagrant  1055 Feb 18 05:46 kintlog.php
drwxrwxrwx 1 vagrant vagrant  4096 Jan 22 01:58 locale
-rwxrwxrwx 1 vagrant vagrant   983 Feb 18 05:42 locale.php
-rwxrwxrwx 1 vagrant vagrant  8061 Feb 20 18:04 logger.php
-rwxrwxrwx 1 vagrant vagrant  1407 Feb 18 05:41 login.php
-rwxrwxrwx 1 vagrant vagrant   473 Feb 18 05:41 logout.php
drwxrwxrwx 1 vagrant vagrant     0 Feb 13 17:55 logs
-rwxrwxrwx 1 vagrant vagrant  6622 Feb 20 17:25 package_list.php
-rwxrwxrwx 1 vagrant vagrant  8379 Feb 20 18:04 packageResult.php
drwxrwxrwx 1 vagrant vagrant  4096 Feb 22 04:27 parts
-rwxrwxrwx 1 vagrant vagrant  7680 Feb 18 05:42 parts-sample.php
-rwxrwxrwx 1 vagrant vagrant  5834 Feb 20 17:00 profile.php
-rwxrwxrwx 1 vagrant vagrant  5853 Feb 18 05:41 rd_listpage.php
-rwxrwxrwx 1 vagrant vagrant 14420 Feb 18 05:41 recipe_list.php
drwxrwxrwx 1 vagrant vagrant  4096 Feb 20 17:00 sass
drwxrwxrwx 1 vagrant vagrant     0 Jan  6 16:25 .sass-cache
-rwxrwxrwx 1 vagrant vagrant  2842 Feb 18 05:41 settings.php
-rwxrwxrwx 1 vagrant vagrant 11757 Feb 20 17:25 target_list.php
-rwxrwxrwx 1 vagrant vagrant 14500 Feb 20 17:00 task_list.php
-rwxrwxrwx 1 vagrant vagrant  4279 Feb 18 05:41 taskResultModal.php
-rwxrwxrwx 1 vagrant vagrant  1022 Feb 18 05:41 template.php
drwxrwxrwx 1 vagrant vagrant  4096 Feb  9 17:06 test
drwxrwxrwx 1 vagrant vagrant  4096 Feb 20 17:22 ts
-rwxrwxrwx 1 vagrant vagrant  9555 Feb 18 05:41 variable_list.php
-rwxrwxrwx 1 vagrant vagrant    45 Dec  3 02:26 watch-scss.bat
```

**Comment by aliceinwire** [comment]
https://github.com/eisen-dev/eisen_front/issues/53

**Comment by aliceinwire** [comment]
https://github.com/eisen-dev/eisen_front/pull/54

**Comment by aliceinwire** [comment]
chmod 777 /vagrant/webd/

**Comment by ytooyama** [comment]
デプロイし直すのでちょっとだけお待ちください

**Comment by ytooyama** [comment]
cd /vagrant && ls -laの結果
```
$ cd /vagrant/
vagrant@vagrant-ubuntu-precise-64:/vagrant$ ls -la
total 164
drwxr-xr-x  1 vagrant vagrant   850 Mar  1 02:18 .
drwxr-xr-x 24 root    root     4096 Mar  1 05:37 ..
-rw-r--r--  1 vagrant vagrant   134 Feb 29 08:51 bower.json
-rw-r--r--  1 vagrant vagrant   487 Feb 29 08:51 .codeclimate.yml
-rw-r--r--  1 vagrant vagrant   310 Feb 29 08:51 composer.json
-rw-r--r--  1 vagrant vagrant 64914 Mar  1 00:47 composer.lock
drwxr-xr-x  1 vagrant vagrant   442 Feb 29 08:51 .git
-rw-r--r--  1 vagrant vagrant   195 Feb 29 08:51 .gitignore
-rw-r--r--  1 vagrant vagrant 35147 Feb 29 08:51 GPL-LICENSE.txt
-rw-r--r--  1 vagrant vagrant    92 Feb 29 08:51 LICENSE.md
-rw-r--r--  1 vagrant vagrant  1134 Feb 29 08:51 MIT-LICENSE.txt
-rw-r--r--  1 vagrant vagrant   718 Mar  1 05:40 npm-debug.log
-rw-r--r--  1 vagrant vagrant   223 Feb 29 08:51 phpunit.xml
-rw-r--r--  1 vagrant vagrant   361 Feb 29 08:51 poMake.sh
-rw-r--r--  1 vagrant vagrant   216 Feb 29 08:51 .project
-rw-r--r--  1 vagrant vagrant  1423 Feb 29 08:51 README.md
-rw-r--r--  1 vagrant vagrant    25 Feb 29 08:51 requirement.txt
-rw-r--r--  1 vagrant vagrant  3812 Mar  1 02:23 test1
drwxr-xr-x  1 vagrant vagrant   136 Feb 29 08:51 tests
-rw-r--r--  1 vagrant vagrant  2871 Feb 29 08:51 tslint.json
drwxr-xr-x  1 vagrant vagrant   136 Feb 29 08:51 vagrant
drwxr-xr-x  1 vagrant vagrant   102 Mar  1 00:37 .vagrant
-rw-r--r--  1 vagrant vagrant  3199 Feb 29 08:51 Vagrantfile
drwxr-xr-x  1 vagrant vagrant   680 Mar  1 05:40 vendor
drwxr-xr-x  1 vagrant vagrant  1190 Mar  1 01:23 webd
```

**Comment by ytooyama** [comment]
vagrant@vagrant-ubuntu-precise-64:/vagrant$ sudo chmod 777 /vagrant/webd/
http://localhost:8080/init-setup1.php にアクセス
設定して次に進む

```
Warning: file_put_contents(connect.php): failed to open stream: Permission denied in /vagrant/webd/init-setup2.php on line 38

Warning: require_once(/vagrant/webd/connect.php): failed to open stream: No such file or directory in /vagrant/webd/init-setup2.php on line 40

Fatal error: require_once(): Failed opening required '/vagrant/webd/connect.php' (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/webd/init-setup2.php on line 40
```

**Comment by aliceinwire** [comment]
sudo chmod -R 777 /vagrant/

**Comment by ytooyama** [comment]
```
$ sudo chmod -R 777 /vagrant/
```

を実行してみましたが、同じエラーでした。

```
Warning: file_put_contents(connect.php): failed to open stream: Permission denied in /vagrant/webd/init-setup2.php on line 38

Warning: require_once(/vagrant/webd/connect.php): failed to open stream: No such file or directory in /vagrant/webd/init-setup2.php on line 40

Fatal error: require_once(): Failed opening required '/vagrant/webd/connect.php' (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/webd/init-setup2.php on line 40
```

**Comment by aliceinwire** [comment]
chmodできないかもしれないですか

**Comment by aliceinwire** [comment]
config.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=777', 'fmode=775']

**Comment by ytooyama** [comment]
vi eisen_front/Vagrantfile
以下を追記
config.vm.synced_folder ".", "/vagrant", :mount_options => ['dmode=777', 'fmode=775']

vagrant up 
これで、うまくいきました。エラーは起きずにユーザー設定の画面に遷移しました。

**Comment by aliceinwire** [comment]
良かった！

**Comment by ytooyama** [comment]
ログインまでできました
![2016-03-01 06 07 56 00001](https://cloud.githubusercontent.com/assets/6257157/13419176/696cc06a-dfbf-11e5-8222-69d45fbe8c25.png)

**Comment by ytooyama** [comment]
設定画面にいくつかFatal errorが出ています
![2016-03-01 06 10 02 00001](https://cloud.githubusercontent.com/assets/6257157/13419247/d00bcf50-dfbf-11e5-9a0e-fddc291edb7f.png)
![2016-03-01 06 10 11 00001](https://cloud.githubusercontent.com/assets/6257157/13419249/d266a7e8-dfbf-11e5-9faa-303a43d0833f.png)
![2016-03-01 06 10 18 00001](https://cloud.githubusercontent.com/assets/6257157/13419251/d75c91c2-dfbf-11e5-9525-bdead89e1829.png)

**Comment by ytooyama** [comment]
データベースとのコネクションの問題みたいですね。

**Comment by aliceinwire** [comment]
はい、これはまた他のissueですね。
ここに https://github.com/eisen-dev/eisen_front issueを開いてください。

**Comment by aliceinwire** [comment]
はい、monologの問題はデータベーステーブルがまだないです。 
target hostの問題はホストマネージャーが追加してないです。

**Comment by aliceinwire** [comment]
fixed install document by merge https://github.com/eisen-dev/eisen_docs/pull/8
